declare global {
const onDeactivated: typeof import('vue')['onDeactivated']
const onActivated: typeof import('vue')['onActivated']
const defineProps: typeof import('vue')['defineProps']
const toRef: typeof import('vue')['toRef']
const onBeforeUnmount: typeof import('vue')['onBeforeUnmount']
const nextTick: typeof import('vue')['nextTick']
const unref: typeof import('vue')['unref']
const watch: typeof import('vue')['watch']
const onMounted: typeof import('vue')['onMounted']
const ref: typeof import('vue')['ref']
const computed: typeof import('vue')['computed']
const defineComponent: typeof import('vue')['defineComponent']
const reactive: typeof import('vue')['reactive']
const toRefs: typeof import('vue')['toRefs']
const createApp: typeof import('vue')['createApp']
const watchEffect: typeof import('vue')['watchEffect']
const getCurrentInstance: typeof import('vue')['getCurrentInstance']
const useRoute: typeof import('vue-router')['useRoute']
const onBeforeRouteLeave: typeof import('vue-router')['onBeforeRouteLeave']
const useRouter: typeof import('vue-router')['useRouter']
const createWebHistory: typeof import('vue-router')['createWebHistory']
const createRouter: typeof import('vue-router')['createRouter']
}
export {}
