import { writeFileSync } from 'fs';
import { join } from 'path';
const temp = () => {
    return '# generated by vcode';
};

export default (basePath: string) => {
    writeFileSync(join(basePath, 'README.md'), temp());
};
